
services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: library
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_USER: admin
      MYSQL_PASSWORD: passwd2
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 40
      start_period: 5s
    networks:
      - conn

  server:
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/library
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=passwd2
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      db:
        condition: service_healthy
    networks:
      - conn

volumes:
  mysql_data:

networks:
  conn: