spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: admin
    password: passwd2
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: create-drop
    defer-datasource-initialization: true
  jackson:
    time-zone: Europe/Warsaw
  sql:
    init:
      mode: always



server:
  port: 8000