spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: admin
    password: passwd2
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect



server:
  port: 8000